import { ArrowRight, FileText, Lightbulb, Rocket, Sparkles, Users } from "lucide-react";
import { Link } from "react-router-dom";

const templates = [
  { title: "Problem brief", description: "Frame a recurring friction, the people affected, and the outcome worth improving.", prompt: "I want to solve a recurring problem for ", icon: Lightbulb, tone: "bg-amber-50 text-amber-600" },
  { title: "MVP experiment", description: "Turn an early thought into a focused test with one audience and one measurable signal.", prompt: "Help me plan a small MVP experiment for ", icon: Rocket, tone: "bg-indigo-50 text-indigo-600" },
  { title: "Community project", description: "Organize an idea that benefits a group, with clear collaborators and next steps.", prompt: "I want to create a community project that helps ", icon: Users, tone: "bg-emerald-50 text-emerald-600" },
];

export default function TemplatesPage() {
  return <div className="min-h-[calc(100vh-76px)] bg-[#fafaf8] px-5 py-7 sm:px-8 sm:py-10 xl:px-12"><main className="mx-auto max-w-6xl"><header className="max-w-2xl"><p className="text-sm font-semibold text-indigo-600">TEMPLATES</p><h1 className="font-heading mt-2 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">A clear starting point for every spark.</h1><p className="mt-3 text-base leading-7 text-slate-500">Choose a structure, make it your own, and continue in the idea editor. Templates and AI conversations now have separate workspaces.</p></header><section className="mt-9 grid gap-5 md:grid-cols-3">{templates.map(({ title, description, prompt, icon: Icon, tone }) => <article key={title} className="flex min-h-72 flex-col rounded-[28px] border border-slate-100 bg-white p-6 shadow-sm"><span className={`grid size-11 place-items-center rounded-2xl ${tone}`}><Icon size={21} /></span><h2 className="font-heading mt-7 text-xl font-bold text-slate-900">{title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-slate-500">{description}</p><Link to={`/submit?prompt=${encodeURIComponent(prompt)}`} className="mt-7 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-indigo-600 hover:text-indigo-700">Use template <ArrowRight size={16} /></Link></article>)}</section><section className="mt-8 flex flex-col gap-4 rounded-[28px] border border-violet-100 bg-gradient-to-r from-violet-50 to-indigo-50 p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-2xl bg-white text-violet-600 shadow-sm"><Sparkles size={20} /></span><div><h2 className="font-heading font-bold text-slate-900">Need a conversation instead?</h2><p className="mt-1 text-sm text-slate-500">Open AI Studio for open-ended exploration.</p></div></div><Link to="/ai-studio" className="inline-flex min-h-11 items-center justify-center rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white hover:bg-indigo-700">Open AI Studio</Link></section><section className="mt-6 rounded-[28px] border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-slate-100 text-slate-600"><FileText size={18} /></span><div><h2 className="font-heading font-bold text-slate-900">How templates work</h2><p className="mt-1 text-sm text-slate-500">A template pre-fills your idea description; it never publishes an idea for you.</p></div></div></section></main></div>;
}
