import { BrowserRouter, Routes, Route } from "react-router-dom";
import { AuthProvider } from "./context/AuthContext";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
import TrustedBy from "./components/TrustedBy";
import CoreCapabilities from "./components/CoreCapabilities";
import ThreeStages from "./components/ThreeStages";
import SocialProof from "./components/SocialProof";
import CTABanner from "./components/CTABanner";
import LoginPage from "./pages/LoginPage";
import RegisterPage from "./pages/RegisterPage";
import DashboardPage from "./pages/DashboardPage";
import IdeasFeedPage from "./pages/IdeasFeedPage";
import IdeaDetailPage from "./pages/IdeaDetailPage";
import UserProfilePage from "./pages/UserProfilePage";
import SubmitIdeaPage from "./pages/SubmitIdeaPage";

function Home() {
  return (
    <main className="min-h-screen bg-white">
      <Hero />
      <TrustedBy />
      <CoreCapabilities />
      <ThreeStages />
      <SocialProof />
      <CTABanner />
    </main>
  );
}

function App() {
  return (
    <BrowserRouter>
      <AuthProvider>
        <div className="font-sans antialiased bg-surface flex flex-col min-h-screen">
          <Routes>
            {/* Auth pages — rendered WITHOUT Navbar/Footer for full-page immersion */}
            <Route path="/login" element={<LoginPage />} />
            <Route path="/register" element={<RegisterPage />} />

            {/* Platform pages generated by Stitch MCP (they include their own layout/nav) */}
            <Route path="/dashboard" element={<DashboardPage />} />
            <Route path="/explore" element={<IdeasFeedPage />} />
            <Route path="/idea/:id" element={<IdeaDetailPage />} />
            <Route path="/profile" element={<UserProfilePage />} />
            <Route path="/submit" element={<SubmitIdeaPage />} />

            {/* All other pages — rendered WITH Navbar/Footer */}
            <Route
              path="*"
              element={
                <>
                  <Navbar />
                  <div className="flex-1 mt-16 sm:mt-18">
                    <Routes>
                      <Route path="/" element={<Home />} />
                    </Routes>
                  </div>
                  <Footer />
                </>
              }
            />
          </Routes>
        </div>
      </AuthProvider>
    </BrowserRouter>
  );
}

export default App;
